var fieldConfigs = [ //
  {
    "name": "冷弯信息",
    "fields": [{
      "groupName": "基础数据",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        },
        {
          "name": "标段名称",
          "field": "tendersName"
        },
        {
          "name": "管线名称",
          "field": "pipelineName"
        },
        {
          "name": "线路段/穿跨越",
          "field": "pipeSegmentOrCrossName"
        },
        {
          "name": "施工单位",
          "field": "constructUnitName"
        },
        {
          "name": "监理单位",
          "field": "supervisionUnitName"
        },
        {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        },
        {
          "name": "采集日期",
          "field": "collectionDate"
        },
        {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "冷弯信息数据",
      "fileds": [{
          "name": "原材料钢管编号",
          "field": "pipeCode"
        },
        {
          "name": "冷湾编号",
          "field": "pipeColdBendingCode"
        },
        {
          "name": "管子弯曲设计标准",
          "field": "pipeBendingStandards"
        },
        {
          "name": "曲率半径(mm)",
          "field": "bendingRadius"
        },
        {
          "name": "弯曲角度(°)",
          "field": "bendingAngle"
        },
        {
          "name": "曲线长度(mm)",
          "field": "curveLength"
        },
        {
          "name": "直管段最小长度(m)",
          "field": "straightPipeLength"
        },
        {
          "name": "椭圆率(%)",
          "field": "ellipticity"
        },
        {
          "name": "壁厚减薄率(%)",
          "field": "wallThicknessRedurate"
        },
        {
          "name": "长度(m)",
          "field": "pipeLength"
        },
        {
          "name": "管径(mm)",
          "field": "pipeDiameter"
        },
        {
          "name": "壁厚(mm)",
          "field": "wallThickness"
        },
        {
          "name": "制作日期",
          "field": "produceDate"
        }
      ]
    }]
  },
  {
    "name": "焊口信息记录",
    "fields": [{
      "groupName": "基础数据",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        }, {
          "name": "标段名称",
          "field": "tendersName"
        }, {
          "name": "管线名称",
          "field": "pipelineName"
        }, {
          "name": "线路段名称",
          "field": "pipeSegmentOrCrossName"
        }, {
          "name": "施工单位",
          "field": "constructUnitName"
        }, {
          "name": "施工机组代号",
          "field": "workUnitCode"
        }, {
          "name": "施工日期",
          "field": "constructDate"
        }, {
          "name": "盖面人员",
          "field": "coverName"
        }, {
          "name": "填充人员",
          "field": "padderName"
        }, {
          "name": "打底人员",
          "field": "renderName"
        },
        {
          "name": "监理单位",
          "field": "supervisionUnitName"
        }, {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        }, {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "采集日期",
          "field": "collectionDate"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "位置数据",
      "fileds": [{
        "name": "桩号",
        "field": "medianStakeCode"
      }, {
        "name": "相对桩位置",
        "field": "relativeMileage"
      }]
    }, {
      "groupName": "焊口数据",
      "fileds": [{
          "name": "焊口编号",
          "field": "weldCode"
        }, {
          "name": "焊口类型",
          "field": "weldTypeName"
        }, {
          "name": "焊接方式",
          "field": "weldMethodName"
        }, {
          "name": "前管件类型",
          "field": "frontPipeTypeName"
        }, {
          "name": "前管件编号",
          "field": "frontPipeCode"
        }, {
          "name": "后管件类型",
          "field": "backPipeTypeName"
        }, {
          "name": "后管件编号",
          "field": "backPipeCode"
        },
        {
          "name": "焊条批号",
          "field": "weldRodBatchNum"
        }, {
          "name": "焊丝批号",
          "field": "weldWireBatchNum"
        }, {
          "name": "焊接工艺规格",
          "field": "weldProduceCode"
        }, {
          "name": "外观质量检查",
          "field": "surfaceCheck"
        },
        {
          "name": "是否金口",
          "field": "isGoldeJoint"
        }, {
          "name": "是否连头口",
          "field": "isPipeHead"
        }
      ]
    }]
  },
  {
    "name": "焊口返修信息记录",
    "fields": [{
      "groupName": "基础数据",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        }, {
          "name": "标段名称",
          "field": "tendersName"
        }, {
          "name": "管线名称",
          "field": "pipelineName"
        }, {
          "name": "线路段名称",
          "field": "pipeSegmentOrCrossName"
        },
        {
          "name": "施工单位",
          "field": "constructUnitName"
        }, {
          "name": "施工机组代号",
          "field": "workUnitName"
        }, {
          "name": "焊接日期",
          "field": "weldDate"
        }, {
          "name": "打底人员",
          "field": "padderName"
        }, {
          "name": "盖面人员",
          "field": "renderName"
        }, {
          "name": "填充人员",
          "field": "coverName"
        }, {
          "name": "监理单位",
          "field": "supervisionUnitName"
        }, {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        }, {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "采集日期",
          "field": "collectionDate"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "返修数据",
      "fileds": [{
        "name": "返修口编号",
        "field": "weldCode"
      }, {
        "name": "返修后焊口编号",
        "field": "reworkWeldCode"
      }, {
        "name": "焊条批号",
        "field": "weldRodBatchNum"
      }, {
        "name": "焊丝批号",
        "field": "weldWireBatchNum"
      }, {
        "name": "焊接工艺规程",
        "field": "weldProduceCode"
      }]
    }]
  },
  {
    "name": "焊口割口信息记录",
    "fields": [{
      "groupName": "基础数据",
      "fileds": [{
        "name": "项目名称",
        "field": "projectName"
      }, {
        "name": "标段名称",
        "field": "tendersName"
      }, {
        "name": "管线名称",
        "field": "pipelineName"
      }, {
        "name": "线路段名称",
        "field": "pipeSegmentOrCrossName"
      }, {
        "name": "施工单位",
        "field": "constructUnitName"
      }, {
        "name": "施工机组",
        "field": "workUnitCode"
      }, {
        "name": "监理单位",
        "field": "supervisionUnitName"
      }, {
        "name": "监理工程师",
        "field": "supervisionEngineer"
      }, {
        "name": "采集人员",
        "field": "collectionPerson"
      }, {
        "name": "采集日期",
        "field": "collectionDate"
      }, {
        "name": "审核状态",
        "field": "approveStatus"
      }]
    }, {
      "groupName": "焊口割口数据",
      "fileds": [{
        "name": "割口编号",
        "field": "weldCode"
      }, {
        "name": "割口日期",
        "field": "cutWeldDate"
      }, {
        "name": "前焊口编号",
        "field": "frontWeldCode"
      }, {
        "name": "后焊口编号",
        "field": "backWeldCode"
      }]
    }]
  },
  {
    "name": "钢管切管信息记录",
    "fields": [{
      "groupName": "基础数据",
      "fileds": [{
        "name": "项目名称",
        "field": "projectName"
      }, {
        "name": "标段名称",
        "field": "tendersName"
      }, {
        "name": "管线名称",
        "field": "pipelineName"
      }, {
        "name": "钢管编号",
        "field": "pipeCode"
      }, {
        "name": "管径(mm)",
        "field": "pipeDiameter"
      }, {
        "name": "壁厚(mm)",
        "field": "wallThickness"
      }, {
        "name": "分割段数(段)",
        "field": "segmentsNum"
      }, {
        "name": "第一段长度(m)",
        "field": "firstParagraphLength"
      }, {
        "name": "第二段长度(m)",
        "field": "secondParagraphLength"
      }, {
        "name": "第三段长度(m)",
        "field": "thirdParagraphLength"
      }, {
        "name": "第四段长度(m)",
        "field": "fourthParagraphLength"
      }, {
        "name": "第五段长度(m)",
        "field": "fifthParagraphLength"
      }, {
        "name": "审核状态",
        "field": "approveStatus"
      }]
    }]
  },
  {
    "name": "焊口测量成果信息记录",
    "fields": [{
      "groupName": "基础数据",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        }, {
          "name": "标段名称",
          "field": "tendersName"
        }, {
          "name": "管线名称",
          "field": "pipelineName"
        }, {
          "name": "线路段名称",
          "field": "pipeSegmentOrCrossName"
        }, {
          "name": "焊口编号",
          "field": "weldCode"
        }, {
          "name": "施工单位",
          "field": "constructUnitName"
        }, {
          "name": "施工机组代号",
          "field": "workUnitCode"
        },
        {
          "name": "监理单位",
          "field": "supervisionUnitName"
        }, {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        }, {
          "name": "测量人",
          "field": "surveyCrew"
        }, {
          "name": "测量日期",
          "field": "surveyDate"
        }, {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "采集日期",
          "field": "collectionDate"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "位置数据",
      "fileds": [{
        "name": "桩号",
        "field": "medianStakeCode"
      }, {
        "name": "相对桩位置",
        "field": "relativeMileage"
      }, {
        "name": "坐标X",
        "field": "pointx"
      }, {
        "name": "坐标Y",
        "field": "pointy"
      }]
    }, {
      "groupName": "中线成果数据",
      "fileds": [{
        "name": "地表高程",
        "field": "surfaceeLevation"
      }, {
        "name": "管顶高程",
        "field": "pipeTopElevation"
      }, {
        "name": "埋深",
        "field": "buriedDepth"
      }]
    }]
  }, {
    "name": "射线检测",
    "fields": [{
      "groupName": "基础数据",
      "fileds": [{
        "field": "projectName",
        "name": "项目名称"
      }, {
        "field": "tendersName",
        "name": "标段名称"
      }, {
        "field": "pipelineName",
        "name": "管线名称"
      }, {
        "field": "pipeSegmentOrCrossName",
        "name": "线路段/穿跨越"
      }, {
        "field": "weldCode",
        "name": "焊口编号"
      }, {
        "field": "detectionReportNum",
        "name": "检测报告编号"
      }, {
        "field": "detectionDeta",
        "name": "检测日期"
      }, {
        "field": "detectionTypeName",
        "name": "检测类型"
      }, {
        "field": "evaluationGradeName",
        "name": "评定等级"
      }, {
        "field": "evaluationResult",
        "name": "评定结果"
      }, {
        "field": "detectionDispose",
        "name": "检测处置"
      }, {
        "field": "detectionUnitName",
        "name": "检测单位"
      }, {
        "field": "detectionPerson",
        "name": "检测人员"
      }, {
        "field": "supervisionUnitName",
        "name": "监理单位"
      }, {
        "field": "supervisionEngineer",
        "name": "监理工程师"
      }, {
        "field": "collectionDate",
        "name": "采集日期"
      }, {
        "field": "approveStatus",
        "name": "审核状态"
      }]
    }, {
      "groupName": "缺陷信息",
      "groupS": "raySubList",
      "fileds": [{
        "field": "defectPosition",
        "name": "缺陷位置"
      }, {
        "field": "defectPropertiesName",
        "name": "缺陷性质"
      }, {
        "field": "defectSize",
        "name": "缺陷尺寸(mm/mm²/点)"
      }]
    }]
  }, {
    "name": "超声波检测",
    "fields": [{
      "groupName": "超声波检测基本信息",
      "fileds": [{
        "field": "projectName",
        "name": "项目名称"
      }, {
        "field": "tendersName",
        "name": "标段名称"
      }, {
        "field": "pipelineName",
        "name": "管线名称"
      }, {
        "field": "pipeSegmentOrCrossName",
        "name": "线路段/穿跨越"
      }, {
        "field": "weldCode",
        "name": "焊口编号"
      }, {
        "field": "detectionReportNum",
        "name": "检测报告编号"
      }, {
        "field": "detectionDeta",
        "name": "检测日期"
      }, {
        "field": "detectionTypeName",
        "name": "检测类型"
      }, {
        "field": "evaluationGradeName",
        "name": "评定等级"
      }, {
        "field": "evaluationResult",
        "name": "评定结果"
      }, {
        "field": "detectionDispose",
        "name": "检测处置"
      }, {
        "field": "detectionLength",
        "name": "检测长度(mm)"
      }, {
        "field": "detectionUnitName",
        "name": "检测单位"
      }, {
        "field": "detectionPerson",
        "name": "检测人员"
      }, {
        "field": "supervisionUnitName",
        "name": "监理单位"
      }, {
        "field": "supervisionEngineer",
        "name": "监理工程师"
      }, {
        "field": "collectionDate",
        "name": "采集日期"
      }, {
        "field": "approveStatus",
        "name": "审核状态"
      }]
    }, {
      "groupName": "缺陷信息",
      "groupS": "ultrasonicSubList",
      "fileds": [{
        "field": "defectPosition",
        "name": "缺陷位置"
      }, {
        "field": "defectPropertiesName",
        "name": "缺陷性质"
      }, {
        "field": "defectSize",
        "name": "缺陷尺寸(mm/mm²/点)"
      }]
    }]
  }, {
    "name": "磁粉检测",
    "fields": [{
      "groupName": "磁粉检测基本信息",
      "fileds": [{
        "field": "projectName",
        "name": "项目名称"
      }, {
        "field": "tendersName",
        "name": "标段名称"
      }, {
        "field": "pipelineName",
        "name": "管线名称"
      }, {
        "field": "pipeSegmentOrCrossName",
        "name": "线路段/穿跨越"
      }, {
        "field": "weldCode",
        "name": "焊口编号"
      }, {
        "field": "detectionReportNum",
        "name": "检测报告编号"
      }, {
        "field": "detectionDeta",
        "name": "检测日期"
      }, {
        "field": "evaluationResult",
        "name": "评定结果"
      }, {
        "field": "detectionDispose",
        "name": "检测处置"
      }, {
        "field": "detectionLength",
        "name": "检测长度(mm)"
      }, {
        "field": "detectionUnitName",
        "name": "检测单位"
      }, {
        "field": "detectionPerson",
        "name": "检测人员"
      }, {
        "field": "supervisionUnitName",
        "name": "监理单位"
      }, {
        "field": "supervisionEngineer",
        "name": "监理工程师"
      }, {
        "field": "collectionDate",
        "name": "采集日期"
      }, {
        "field": "approveStatus",
        "name": "审核状态"
      }]
    }, {
      "groupName": "缺陷信息",
      "groupS": "powderSubList",
      "fileds": [{
        "field": "defectPosition",
        "name": "缺陷位置"
      }, {
        "field": "defectPropertiesName",
        "name": "缺陷性质"
      }, {
        "field": "defectSize",
        "name": "缺陷尺寸(mm/mm²/点)"
      }]
    }]
  }, {
    "name": "渗透检测",
    "fields": [{
      "groupName": "渗透检测基本信息",
      "fileds": [{
        "field": "projectName",
        "name": "项目名称"
      }, {
        "field": "tendersName",
        "name": "标段名称"
      }, {
        "field": "pipelineName",
        "name": "管线名称"
      }, {
        "field": "pipeSegmentOrCrossName",
        "name": "线路段/穿跨越"
      }, {
        "field": "weldCode",
        "name": "焊口编号"
      }, {
        "field": "detectionReportNum",
        "name": "检测报告编号"
      }, {
        "field": "detectionDeta",
        "name": "检测日期"
      }, {
        "field": "detectionTypeName",
        "name": "检测类型"
      }, {
        "field": "evaluationGradeName",
        "name": "评定等级"
      }, {
        "field": "evaluationResult",
        "name": "评定结果"
      }, {
        "field": "detectionDispose",
        "name": "检测处置"
      }, {
        "field": "detectionLength",
        "name": "检测长度(mm)"
      }, {
        "field": "detectionUnitName",
        "name": "检测单位"
      }, {
        "field": "detectionPerson",
        "name": "检测人员"
      }, {
        "field": "supervisionUnitName",
        "name": "监理单位"
      }, {
        "field": "supervisionEngineer",
        "name": "监理工程师"
      }, {
        "field": "collectionDate",
        "name": "采集日期"
      }, {
        "field": "approveStatus",
        "name": "审核状态"
      }]
    }, {
      "groupName": "缺陷信息",
      "groupS": "infiltrationSubList",
      "fileds": [{
        "field": "defectPosition",
        "name": "缺陷位置"
      }, {
        "field": "defectPropertiesName",
        "name": "缺陷性质"
      }, {
        "field": "defectSize",
        "name": "缺陷尺寸(mm/mm²/点)"
      }]
    }]
  }, {
    "name": "相控阵超声波检测",
    "fields": [{
      "groupName": "相控阵超声波检测基本信息",
      "fileds": [{
        "name": "项目名称",
        "field": "projectName"
      }, {
        "name": "标段名称",
        "field": "tendersName"
      }, {
        "name": "管线名称",
        "field": "pipelineName"
      }, {
        "name": "线路段/穿跨越名称",
        "field": "pipeSegmentOrCrossName"
      }, {
        "name": "焊口编号",
        "field": "weldCode"
      }, {
        "name": "检测报告编号",
        "field": "detectionReportNum"
      }, {
        "name": "检测日期",
        "field": "detectionDeta"
      }, {
        "name": "检测类型",
        "field": "detectionTypeName"
      }, {
        "name": "检测处置",
        "field": "detectionDispose"
      }, {
        "name": "评定结果",
        "field": "evaluationResult"
      }, {
        "field": "detectionLength",
        "name": '检测长度(mm)'
      }, {
        "name": "检测单位",
        "field": "detectionUnitName"
      }, {
        "name": "检测人员",
        "field": "detectionPerson"
      }, {
        "name": "审核人员",
        "field": "auditor"
      }, {
        "name": "监理单位",
        "field": "supervisionUnitName"
      }, {
        "name": "监理工程师",
        "field": "supervisionEngineer"
      }, {
        "name": "采集日期",
        "field": "collectionDate"
      }, {
        "field": "approveStatus",
        "name": "审核状态"
      }]
    }, {
      "groupName": "缺陷信息",
      "groupS": "paUltrasonicSubList",
      "fileds": [{
        "field": "defectPosition",
        "name": "缺陷位置"
      }, {
        "field": "amplitudeRegion",
        "name": "振幅区域"
      }, {
        "field": "defectLength",
        "name": "缺陷长度(mm)"
      }, {
        "field": "defectDepth",
        "name": "缺陷深度(mm)"
      }, {
        "field": "height",
        "name": "自身高度(mm)"
      }]
    }]
  }, {
    "name": "全自动超声波检测",
    "fields": [{
      "groupName": "全自动超声波检测基本信息",
      "fileds": [{
        "name": "项目名称",
        "field": "projectName"
      }, {
        "name": "标段名称",
        "field": "tendersName"
      }, {
        "name": "管线名称",
        "field": "pipelineName"
      }, {
        "name": "线路段/穿跨越名称",
        "field": "pipeSegmentOrCrossName"
      }, {
        "name": "焊口编号",
        "field": "weldCode"
      }, {
        "name": "检测报告编号",
        "field": "detectionReportNum"
      }, {
        "name": "检测日期",
        "field": "detectionDeta"
      }, {
        "name": "检测类型",
        "field": "detectionTypeName"
      }, {
        "name": "检测处置",
        "field": "detectionDispose"
      }, {
        "name": "评定结果",
        "field": "evaluationResult"
      }, {
        "name": "检测单位",
        "field": "detectionUnitName"
      }, {
        "name": "检测人员",
        "field": "detectionPerson"
      }, {
        "name": "审核人员",
        "field": "auditor"
      }, {
        "name": "监理单位",
        "field": "supervisionUnitName"
      }, {
        "name": "监理工程师",
        "field": "supervisionEngineer"
      }, {
        "name": "采集日期",
        "field": "collectionDate"
      }, {
        "field": "approveStatus",
        "name": "审核状态"
      }]
    }, {
      "groupName": "缺陷信息",
      "groupS": "faUltrasonicSubList",
      "fileds": [{
        "field": "defectPosition",
        "name": "缺陷位置"
      }, {
        "field": "amplitudeRegion",
        "name": "振幅区域"
      }, {
        "field": "defectLength",
        "name": "缺陷长度(mm)"
      }, {
        "field": "defectDepth",
        "name": "缺陷深度(mm)"
      }, {
        "field": "height",
        "name": "自身高度(mm)"
      }]
    }]
  }, {
    "name": "测量放线",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
        "field": "projectName",
        "name": "项目名称"
      }, {
        "field": "tendersName",
        "name": "标段名称"
      }, {
        "field": "pipelineName",
        "name": "管线名称"
      }, {
        "field": "pipeSegmentOrCrossName",
        "name": "线路段"
      }, {
        "field": "constructUnitName",
        "name": "施工单位"
      }, {
        "field": "constructDate",
        "name": "施工日期"
      }, {
        "field": "collectionPerson",
        "name": "采集人员"
      }, {
        "field": "collectionDate",
        "name": "采集日期"
      }, {
        "field": "supervisionUnitName",
        "name": "监理单位"
      }, {
        "field": "supervisionEngineer",
        "name": "监理工程师"
      }, {
        "name": "审核状态",
        "field": "approveStatus"
      }]
    }, {
      "groupName": "位置信息",
      "fileds": [{
        "field": "medianStakeCode",
        "name": "桩号"
      }]
    }, {
      "groupName": "测量放线数据",
      "fileds": [{
        "field": "relativeMileage",
        "name": "里程"
      }, {
        "field": "measuredAngle",
        "name": "实测转角(°)"
      }, {
        "field": "drawingAngle",
        "name": "图纸转角(°)"
      }, {
        "field": "leftWidth",
        "name": "管道中心线左侧放线宽度(m)"
      }, {
        "field": "rightWidth",
        "name": "管道中心线右侧放线宽度(m)"
      }]
    }]
  }, {
    "name": "管沟开挖",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
        "field": "projectName",
        "name": "项目名称"
      }, {
        "field": "tendersName",
        "name": "标段名称"
      }, {
        "field": "pipelineName",
        "name": "管线名称"
      }, {
        "field": "pipeSegmentOrCrossName",
        "name": "线路段"
      }, {
        "field": "constructUnitName",
        "name": "施工单位"
      }, {
        "field": "constructDate",
        "name": "施工日期"
      }, {
        "field": "collectionPerson",
        "name": "采集人员"
      }, {
        "field": "collectionDate",
        "name": "采集日期"
      }, {
        "field": "supervisionUnitName",
        "name": "监理单位"
      }, {
        "field": "supervisionEngineer",
        "name": "监理工程师"
      }, {
        "name": "审核状态",
        "field": "approveStatus"
      }]
    }, {
      "groupName": "位置信息",
      "fileds": [{
        "name": "起始桩号",
        "field": "startMedianStakeName"
      }, {
        "name": "相对起始桩里程(m)",
        "field": "startRelativeMileage"
      }, {
        "name": "结束桩号",
        "field": "endMedianStakeName"
      }, {
        "name": "相对结束桩里程(m)",
        "field": "endRelativeMileage"
      }]
    }, {
      "groupName": "管沟开挖数据",
      "fileds": [{
        "name": "土壤类别",
        "field": "soilType"
      }, {
        "name": "管沟深度(m)",
        "field": "pipeTrenchDepth"
      }, {
        "name": "沟底宽度(m)",
        "field": "grooveWidth"
      }, {
        "name": "放坡角度(°)",
        "field": "slopeAngle"
      }, {
        "name": "沟底长度(m)",
        "field": "grooveHeight"
      }, {
        "name": "设计转角(°)",
        "field": "designCornerAngle"
      }, {
        "name": "实际转角(°)",
        "field": "actualCornerAngle"
      }, {
        "name": "结论",
        "field": "conclusion"
      }, {
        "name": "检查验收意见",
        "field": "acceptanceOpinion"
      }]
    }]
  }, {
    "name": "管沟回填",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
        "field": "projectName",
        "name": "项目名称"
      }, {
        "field": "tendersName",
        "name": "标段名称"
      }, {
        "field": "pipelineName",
        "name": "管线名称"
      }, {
        "field": "pipeSegmentOrCrossName",
        "name": "线路段"
      }, {
        "field": "constructUnitName",
        "name": "施工单位"
      }, {
        "field": "constructDate",
        "name": "施工日期"
      }, {
        "field": "collectionPerson",
        "name": "采集人员"
      }, {
        "field": "collectionDate",
        "name": "采集日期"
      }, {
        "field": "supervisionUnitName",
        "name": "监理单位"
      }, {
        "field": "supervisionEngineer",
        "name": "监理工程师"
      }, {
        "name": "审核状态",
        "field": "approveStatus"
      }]
    }, {
      "groupName": "位置信息",
      "fileds": [{
        "name": "起始桩号",
        "field": "startMedianStakeName"
      }, {
        "name": "结束桩号",
        "field": "endMedianStakeName"
      }, {
        "name": "相对起始桩里程(m)",
        "field": "startRelativeMileage"
      }, {
        "name": "相对结束桩里程(m)",
        "field": "endRelativeMileage"
      }]
    }, {
      "groupName": "管沟回填数据",
      "fileds": [{
        "name": "回填长度(m)",
        "field": "backfillLength"
      }, {
        "name": "细土回填厚度(mm)",
        "field": "backfillThickness"
      }, {
        "name": "一次回填厚度(mm)",
        "field": "oneBackfillThickness"
      }, {
        "name": "二次回填厚度(mm)",
        "field": "twoBackfillThickness"
      }, {
        "name": "埋地标识类型",
        "field": "signTypeName"
      }, {
        "name": "标识长度(m)",
        "field": "signLength"
      }, {
        "name": "标识埋深(m)",
        "field": "signDepth"
      }]
    }]
  }, {
    "name": "地貌恢复验收",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
        "field": "projectName",
        "name": "项目名称"
      }, {
        "field": "tendersName",
        "name": "标段名称"
      }, {
        "field": "pipelineName",
        "name": "管线名称"
      }, {
        "field": "pipeSegmentOrCrossName",
        "name": "线路段"
      }, {
        "field": "constructUnitName",
        "name": "施工单位"
      }, {
        "field": "constructDate",
        "name": "施工日期"
      }, {
        "field": "collectionPerson",
        "name": "采集人员"
      }, {
        "field": "collectionDate",
        "name": "采集日期"
      }, {
        "field": "supervisionUnitName",
        "name": "监理单位"
      }, {
        "field": "supervisionEngineer",
        "name": "监理工程师"
      }, {
        "name": "审核状态",
        "field": "approveStatus"
      }]
    }, {
      "groupName": "位置信息",
      "fileds": [{
        "name": "起始桩号",
        "field": "startMedianStakeName"
      }, {
        "name": "结束桩号",
        "field": "endMedianStakeName"
      }, {
        "name": "相对起始桩里程(m)",
        "field": "startRelativeMileage"
      }, {
        "name": "相对结束桩里程(m)",
        "field": "endRelativeMileage"
      }]
    }, {
      "groupName": "地貌恢复验收数据",
      "fileds": [{
        "name": "长度(m)",
        "field": "length"
      }, {
        "name": "经过地区",
        "field": "region"
      }, {
        "name": "证书编号",
        "field": "certificateNum"
      }]
    }]
  }, {
    "name": "保温",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
        "field": "projectName",
        "name": "项目名称"
      }, {
        "field": "tendersName",
        "name": "标段名称"
      }, {
        "field": "pipelineName",
        "name": "管线名称"
      }, {
        "field": "pipeSegmentOrCrossName",
        "name": "线路段"
      }, {
        "field": "constructUnitName",
        "name": "施工单位"
      }, {
        "field": "constructDate",
        "name": "施工日期"
      }, {
        "field": "collectionPerson",
        "name": "采集人员"
      }, {
        "field": "collectionDate",
        "name": "采集日期"
      }, {
        "field": "supervisionUnitName",
        "name": "监理单位"
      }, {
        "field": "supervisionEngineer",
        "name": "监理工程师"
      }, {
        "name": "审核状态",
        "field": "approveStatus"
      }]
    }, {
      "groupName": "位置信息",
      "fileds": [{
        "name": "起始桩号",
        "field": "startMedianStakeName"
      }, {
        "name": "结束桩号",
        "field": "endMedianStakeName"
      }, {
        "name": "相对起始桩里程(m)",
        "field": "startRelativeMileage"
      }, {
        "name": "相对结束桩里程(m)",
        "field": "endRelativeMileage"
      }]
    }, {
      "groupName": "保温数据",
      "fileds": [{
        "name": "保温材料",
        "field": "insulationMaterialName"
      }, {
        "name": "保温层厚度(mm)",
        "field": "insulationThickness"
      }, {
        "name": "防护层结构",
        "field": "protectiveTapeName"
      }, {
        "name": "防护层厚度(mm)",
        "field": "protectiveThickness"
      }, {
        "name": "保温层生产厂家",
        "field": "manufacturer"
      }, {
        "name": "具体地址",
        "field": "manufacturerAddress"
      }]
    }]
  }, {
    "name": "开挖穿越",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
        "field": "projectName",
        "name": "项目名称"
      }, {
        "field": "tendersName",
        "name": "标段名称"
      }, {
        "field": "pipelineName",
        "name": "管线名称"
      }, {
        "field": "crossName",
        "name": "穿跨越名称"
      }, {
        "field": "commencementDate",
        "name": "开工日期"
      }, {
        "field": "completionDate",
        "name": "完工日期"
      }, {
        "field": "constructUnitName",
        "name": "施工单位"
      }, {
        "field": "collectionPerson",
        "name": "采集人员"
      }, {
        "field": "collectionDate",
        "name": "采集日期"
      }, {
        "field": "supervisionUnitName",
        "name": "监理单位"
      }, {
        "field": "supervisionEngineer",
        "name": "监理工程师"
      }, {
        "name": "审核状态",
        "field": "approveStatus"
      }]
    }, {
      "groupName": "位置信息",
      "fileds": [{
        "name": "起始桩号",
        "field": "startMedianStakeCode"
      }, {
        "name": "结束桩号",
        "field": "endMedianStakeCode"
      }, {
        "name": "相对起始桩里程(m)",
        "field": "startRelativeMileage"
      }, {
        "name": "相对结束桩里程(m)",
        "field": "endRelativeMileage"
      }, {
        "name": "起始点X坐标",
        "field": "startPointx"
      }, {
        "name": "结束点X坐标",
        "field": "endPointx"
      }, {
        "name": "起始点Y坐标",
        "field": "startPointy"
      }, {
        "name": "结束点Y坐标",
        "field": "endPointy"
      }, {
        "name": "起始点高程(m)",
        "field": "startPointz"
      }, {
        "name": "结束点高程(m)",
        "field": "endPointz"
      }]
    }, {
      "groupName": "穿越信息",
      "fileds": [{
        "name": "穿越物管理单位",
        "field": "crossingDepartment"
      }, {
        "name": "穿越长度(m)",
        "field": "crossLength"
      }, {
        "name": "穿越最大深度(m)",
        "field": "crossMaxLength"
      }, {
        "name": "稳管措施",
        "field": "steadyTubeMeasures"
      }]
    }]
  }, {
    "name": "顶管穿越",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
        "field": "projectName",
        "name": "项目名称"
      }, {
        "field": "tendersName",
        "name": "标段名称"
      }, {
        "field": "pipelineName",
        "name": "管线名称"
      }, {
        "field": "crossName",
        "name": "穿跨越名称"
      }, {
        "field": "commencementDate",
        "name": "开工日期"
      }, {
        "field": "completionDate",
        "name": "完工日期"
      }, {
        "field": "constructUnitName",
        "name": "施工单位"
      }, {
        "field": "collectionPerson",
        "name": "采集人员"
      }, {
        "field": "collectionDate",
        "name": "采集日期"
      }, {
        "field": "supervisionUnitName",
        "name": "监理单位"
      }, {
        "field": "supervisionEngineer",
        "name": "监理工程师"
      }, {
        "name": "审核状态",
        "field": "approveStatus"
      }]
    }, {
      "groupName": "位置信息",
      "fileds": [{
        "name": "起始桩号",
        "field": "startMedianStakeCode"
      }, {
        "name": "结束桩号",
        "field": "endMedianStakeCode"
      }, {
        "name": "相对起始桩里程(m)",
        "field": "startRelativeMileage"
      }, {
        "name": "相对结束桩里程(m)",
        "field": "endRelativeMileage"
      }, {
        "name": "起始点X坐标",
        "field": "startPointx"
      }, {
        "name": "结束点X坐标",
        "field": "endPointx"
      }, {
        "name": "起始点Y坐标",
        "field": "startPointy"
      }, {
        "name": "结束点Y坐标",
        "field": "endPointy"
      }, {
        "name": "起始点高程(m)",
        "field": "startPointz"
      }, {
        "name": "结束点高程(m)",
        "field": "endPointz"
      }]
    }, {
      "groupName": "穿越信息",
      "fileds": [{
        "name": "穿越物管理单位",
        "field": "crossingDepartment"
      }, {
        "name": "穿越长度(m)",
        "field": "crossLength"
      }, {
        "name": "穿越最大深度(m)",
        "field": "crossMaxLength"
      }]
    }]
  }, {
    "name": "箱涵穿越",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
        "field": "projectName",
        "name": "项目名称"
      }, {
        "field": "tendersName",
        "name": "标段名称"
      }, {
        "field": "pipelineName",
        "name": "管线名称"
      }, {
        "field": "crossName",
        "name": "穿跨越名称"
      }, {
        "field": "commencementDate",
        "name": "开工日期"
      }, {
        "field": "completionDate",
        "name": "完工日期"
      }, {
        "field": "constructUnitName",
        "name": "施工单位"
      }, {
        "field": "collectionPerson",
        "name": "采集人员"
      }, {
        "field": "collectionDate",
        "name": "采集日期"
      }, {
        "field": "supervisionUnitName",
        "name": "监理单位"
      }, {
        "field": "supervisionEngineer",
        "name": "监理工程师"
      }, {
        "name": "审核状态",
        "field": "approveStatus"
      }]
    }, {
      "groupName": "位置信息",
      "fileds": [{
        "name": "起始桩号",
        "field": "startMedianStakeCode"
      }, {
        "name": "结束桩号",
        "field": "endMedianStakeCode"
      }, {
        "name": "相对起始桩里程(m)",
        "field": "startRelativeMileage"
      }, {
        "name": "相对结束桩里程(m)",
        "field": "endRelativeMileage"
      }, {
        "name": "起始点X坐标",
        "field": "startPointx"
      }, {
        "name": "结束点X坐标",
        "field": "endPointx"
      }, {
        "name": "起始点Y坐标",
        "field": "startPointy"
      }, {
        "name": "结束点Y坐标",
        "field": "endPointy"
      }, {
        "name": "起始点高程(m)",
        "field": "startPointz"
      }, {
        "name": "结束点高程(m)",
        "field": "endPointz"
      }]
    }, {
      "groupName": "穿越信息",
      "fileds": [{
        "name": "穿越物管理单位",
        "field": "crossingDepartment"
      }, {
        "name": "穿越长度(m)",
        "field": "crossLength"
      }, {
        "name": "穿越最大深度(m)",
        "field": "crossMaxLength"
      }]
    }]
  }, {
    "name": "定向钻穿越",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
        "field": "projectName",
        "name": "项目名称"
      }, {
        "field": "tendersName",
        "name": "标段名称"
      }, {
        "field": "pipelineName",
        "name": "管线名称"
      }, {
        "field": "crossName",
        "name": "穿跨越名称"
      }, {
        "field": "commencementDate",
        "name": "开工日期"
      }, {
        "field": "completionDate",
        "name": "完工日期"
      }, {
        "field": "constructUnitName",
        "name": "施工单位"
      }, {
        "field": "collectionPerson",
        "name": "采集人员"
      }, {
        "field": "collectionDate",
        "name": "采集日期"
      }, {
        "field": "supervisionUnitName",
        "name": "监理单位"
      }, {
        "field": "supervisionEngineer",
        "name": "监理工程师"
      }, {
        "name": "审核状态",
        "field": "approveStatus"
      }]
    }, {
      "groupName": "位置信息",
      "fileds": [{
        "name": "起始桩号",
        "field": "startMedianStakeCode"
      }, {
        "name": "结束桩号",
        "field": "endMedianStakeCode"
      }, {
        "name": "相对起始桩里程(m)",
        "field": "startRelativeMileage"
      }, {
        "name": "相对结束桩里程(m)",
        "field": "endRelativeMileage"
      }, {
        "name": "入土点X坐标",
        "field": "startPointx"
      }, {
        "name": "出土点X坐标",
        "field": "endPointx"
      }, {
        "name": "入土点Y坐标",
        "field": "startPointy"
      }, {
        "name": "出土点Y坐标",
        "field": "endPointy"
      }, {
        "name": "入土点高程(m)",
        "field": "startPointz"
      }, {
        "name": "出土点高程(m)",
        "field": "endPointz"
      }, {
        "name": "入土角",
        "field": "enterAngle"
      }, {
        "name": "出土角",
        "field": "exitAngle"
      }]
    }, {
      "groupName": "穿越信息",
      "fileds": [{
        "name": "穿越物管理单位",
        "field": "crossingDepartment"
      }, {
        "name": "穿越长度(m)",
        "field": "crossLength"
      }, {
        "name": "穿越最大深度(m)",
        "field": "crossMaxLength"
      }]
    }]
  }, {
    "name": "钻爆隧道穿越",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
        "field": "projectName",
        "name": "项目名称"
      }, {
        "field": "tendersName",
        "name": "标段名称"
      }, {
        "field": "pipelineName",
        "name": "管线名称"
      }, {
        "field": "crossName",
        "name": "穿跨越名称"
      }, {
        "field": "commencementDate",
        "name": "开工日期"
      }, {
        "field": "completionDate",
        "name": "完工日期"
      }, {
        "field": "constructUnitName",
        "name": "施工单位"
      }, {
        "field": "collectionPerson",
        "name": "采集人员"
      }, {
        "field": "collectionDate",
        "name": "采集日期"
      }, {
        "field": "supervisionUnitName",
        "name": "监理单位"
      }, {
        "field": "supervisionEngineer",
        "name": "监理工程师"
      }, {
        "name": "审核状态",
        "field": "approveStatus"
      }]
    }, {
      "groupName": "位置信息",
      "fileds": [{
        "name": "起始桩号",
        "field": "startMedianStakeCode"
      }, {
        "name": "结束桩号",
        "field": "endMedianStakeCode"
      }, {
        "name": "相对起始桩里程(m)",
        "field": "startRelativeMileage"
      }, {
        "name": "相对结束桩里程(m)",
        "field": "endRelativeMileage"
      }, {
        "name": "起始点X坐标",
        "field": "startPointx"
      }, {
        "name": "结束点X坐标",
        "field": "endPointx"
      }, {
        "name": "起始点Y坐标",
        "field": "startPointy"
      }, {
        "name": "结束点Y坐标",
        "field": "endPointy"
      }, {
        "name": "起始点高程(m)",
        "field": "startPointz"
      }, {
        "name": "结束点高程(m)",
        "field": "endPointz"
      }]
    }, {
      "groupName": "穿越信息",
      "fileds": [{
        "name": "穿越物管理单位",
        "field": "crossingDepartment"
      }, {
        "name": "穿越长度(m)",
        "field": "crossLength"
      }, {
        "name": "穿越最大深度(m)",
        "field": "crossMaxLength"
      }, {
        "name": "稳管措施",
        "field": "steadyTubeMeasures"
      }, {
        "name": "钻爆围堰等级",
        "field": "cofferdamGrade"
      }, {
        "name": "衬砌形式",
        "field": "liningType"
      }]
    }]
  }, {
    "name": "跨越",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
        "field": "projectName",
        "name": "项目名称"
      }, {
        "field": "tendersName",
        "name": "标段名称"
      }, {
        "field": "pipelineName",
        "name": "管线名称"
      }, {
        "field": "crossName",
        "name": "穿跨越名称"
      }, {
        "field": "commencementDate",
        "name": "开工日期"
      }, {
        "field": "completionDate",
        "name": "完工日期"
      }, {
        "field": "constructUnitName",
        "name": "施工单位"
      }, {
        "field": "collectionPerson",
        "name": "采集人员"
      }, {
        "field": "collectionDate",
        "name": "采集日期"
      }, {
        "field": "supervisionUnitName",
        "name": "监理单位"
      }, {
        "field": "supervisionEngineer",
        "name": "监理工程师"
      }, {
        "name": "审核状态",
        "field": "approveStatus"
      }]
    }, {
      "groupName": "位置信息",
      "fileds": [{
        "name": "起始桩号",
        "field": "startMedianStakeCode"
      }, {
        "name": "结束桩号",
        "field": "endMedianStakeCode"
      }, {
        "name": "相对起始桩里程(m)",
        "field": "startRelativeMileage"
      }, {
        "name": "相对结束桩里程(m)",
        "field": "endRelativeMileage"
      }, {
        "name": "起始点X坐标",
        "field": "startPointx"
      }, {
        "name": "结束点X坐标",
        "field": "endPointx"
      }, {
        "name": "起始点Y坐标",
        "field": "startPointy"
      }, {
        "name": "结束点Y坐标",
        "field": "endPointy"
      }, {
        "name": "起始点高程(m)",
        "field": "startPointz"
      }, {
        "name": "结束点高程(m)",
        "field": "endPointz"
      }]
    }, {
      "groupName": "穿越信息",
      "fileds": [{
        "name": "穿越物管理单位",
        "field": "crossingDepartment"
      }, {
        "name": "穿越长度(m)",
        "field": "crossLength"
      }, {
        "name": "穿越最大深度(m)",
        "field": "crossMaxLength"
      }]
    }]
  }, {
    "name": "盾构隧道穿越",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
        "field": "projectName",
        "name": "项目名称"
      }, {
        "field": "tendersName",
        "name": "标段名称"
      }, {
        "field": "pipelineName",
        "name": "管线名称"
      }, {
        "field": "crossName",
        "name": "穿跨越名称"
      }, {
        "field": "commencementDate",
        "name": "开工日期"
      }, {
        "field": "completionDate",
        "name": "完工日期"
      }, {
        "field": "constructUnitName",
        "name": "施工单位"
      }, {
        "field": "collectionPerson",
        "name": "采集人员"
      }, {
        "field": "collectionDate",
        "name": "采集日期"
      }, {
        "field": "supervisionUnitName",
        "name": "监理单位"
      }, {
        "field": "supervisionEngineer",
        "name": "监理工程师"
      }, {
        "name": "审核状态",
        "field": "approveStatus"
      }]
    }, {
      "groupName": "位置信息",
      "fileds": [{
        "name": "起始桩号",
        "field": "startMedianStakeCode"
      }, {
        "name": "结束桩号",
        "field": "endMedianStakeCode"
      }, {
        "name": "相对起始桩里程(m)",
        "field": "startRelativeMileage"
      }, {
        "name": "相对结束桩里程(m)",
        "field": "endRelativeMileage"
      }, {
        "name": "起始点X坐标",
        "field": "startPointx"
      }, {
        "name": "结束点X坐标",
        "field": "endPointx"
      }, {
        "name": "起始点Y坐标",
        "field": "startPointy"
      }, {
        "name": "结束点Y坐标",
        "field": "endPointy"
      }, {
        "name": "起始点高程(m)",
        "field": "startPointz"
      }, {
        "name": "结束点高程(m)",
        "field": "endPointz"
      }]
    }, {
      "groupName": "穿越信息",
      "fileds": [{
        "name": "穿越物管理单位",
        "field": "crossingDepartment"
      }, {
        "name": "穿越长度(m)",
        "field": "crossLength"
      }, {
        "name": "穿越最大深度(m)",
        "field": "crossMaxLength"
      }]
    }]
  }, {
    "name": "绝缘件",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        }, {
          "name": "标段名称",
          "field": "tendersName"
        }, {
          "name": "管线名称",
          "field": "pipelineName"
        }, {
          "name": "线路段名称",
          "field": "pipeSegmentName"
        }, {
          "name": "施工单位",
          "field": "constructUnitName"
        }, {
          "name": "施工日期",
          "field": "constructDate"
        },
        {
          "name": "监理单位",
          "field": "supervisionUnitName"
        }, {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        }, {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "采集日期",
          "field": "collectionDate"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "位置数据",
      "fileds": [{
        "name": "桩号",
        "field": "medianStakeCode"
      }, {
        "name": "相对桩位置(m)",
        "field": "relativeMileage"
      }, {
        "name": "X坐标",
        "field": "pointx"
      }, {
        "name": "Y坐标",
        "field": "pointy"
      }, {
        "name": "高程(m)",
        "field": "pointz"
      }]
    }, {
      "groupName": "绝缘件数据",
      "fileds": [{
        "name": "绝缘件编号",
        "field": "isolatingPieceCode"
      }, {
        "name": "名称",
        "field": "isolatingPieceName"
      }, {
        "name": "前管件编号",
        "field": "startPipeFittingNum"
      }, {
        "name": "前管件类型",
        "field": "startPipeFittingTypeName"
      }, {
        "name": "后管件编号",
        "field": "endPipeFittingNum"
      }, {
        "name": "后管件类型",
        "field": "endPipeFittingTypeName"
      }]
    }]
  }, {
    "name": "阴极保护电缆",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        }, {
          "name": "标段名称",
          "field": "tendersName"
        }, {
          "name": "管线名称",
          "field": "pipelineName"
        }, {
          "name": "线路段名称",
          "field": "pipeSegmentName"
        }, {
          "name": "施工单位",
          "field": "constructUnitName"
        }, {
          "name": "施工日期",
          "field": "constructDate"
        },
        {
          "name": "监理单位",
          "field": "supervisionUnitName"
        }, {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        }, {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "采集日期",
          "field": "collectionDate"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "位置数据",
      "fileds": [{
        "name": "桩号",
        "field": "medianStakeCode"
      }, {
        "name": "相对桩位置(m)",
        "field": "relativeMileage"
      }]
    }, {
      "groupName": "阴极保护数据",
      "fileds": [{
        "name": "阴保电缆编号",
        "field": "cableCode"
      }, {
        "name": "电缆规格型号",
        "field": "cableSpecification"
      }, {
        "name": "电缆盘号",
        "field": "cableTrayNum"
      }, {
        "name": "电缆批次",
        "field": "cableBatche"
      }, {
        "name": "电缆保护结构",
        "field": "cableStructionName"
      }, {
        "name": "电缆敷设方式",
        "field": "cableLayingMethodName"
      }, {
        "name": "电缆长度(m)",
        "field": "cableLength"
      }, {
        "name": "电缆敷设图编号",
        "field": "cableLayoutCode"
      }, {
        "name": "电缆用途",
        "field": "cableUseName"
      }]
    }]
  }, {
    "name": "牺牲阳极",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        }, {
          "name": "标段名称",
          "field": "tendersName"
        }, {
          "name": "管线名称",
          "field": "pipelineName"
        }, {
          "name": "线路段名称",
          "field": "pipeSegmentName"
        }, {
          "name": "施工单位",
          "field": "constructUnitName"
        }, {
          "name": "施工日期",
          "field": "constructDate"
        },
        {
          "name": "监理单位",
          "field": "supervisionUnitName"
        }, {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        }, {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "采集日期",
          "field": "collectionDate"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "位置数据",
      "fileds": [{
        "name": "桩号",
        "field": "medianStakeCode"
      }, {
        "name": "相对桩位置(m)",
        "field": "relativeMileage"
      }, {
        "name": "X坐标",
        "field": "pointx"
      }, {
        "name": "Y坐标",
        "field": "pointy"
      }, {
        "name": "高程(m)",
        "field": "pointz"
      }]
    }, {
      "groupName": "牺牲阳极数据",
      "fileds": [{
          "name": "阳极编号",
          "field": "anodeCode"
        }, {
          "name": "保护对象",
          "field": "protectObject"
        }, {
          "name": "是否临时",
          "field": "isTemporary"
        }, {
          "name": "设计寿命(年)",
          "field": "designLife"
        }, {
          "name": "牺牲阳极材料",
          "field": "anodeMaterialName"
        }, {
          "name": "牺牲阳极型号",
          "field": "anodeSpecification"
        }, {
          "name": "牺牲阳极数量(支)",
          "field": "andoeQuantity"
        },
        {
          "name": "牺牲阳极单重(kg)",
          "field": "andoeWeight"
        }, {
          "name": "牺牲阳极总重(kg)",
          "field": "totalWeight"
        }, {
          "name": "阳极间距(m)",
          "field": "anodeDistance"
        }, {
          "name": "与管道距离(m)",
          "field": "pipeDistance"
        }, {
          "name": "制造商",
          "field": "manufacture"
        }, {
          "name": "埋设日期",
          "field": "burialDate"
        },
        {
          "name": "阳极埋深(m)",
          "field": "anodeBuriedDepth"
        },
        {
          "name": "铺设长度(m)",
          "field": "layLength"
        },
        {
          "name": "填包料重量(kg)",
          "field": "fillWeight"
        },
        {
          "name": "各接点质量及绝缘情况",
          "field": "insulationQualityName"
        },
        {
          "name": "检查片埋设情况",
          "field": "tabletsCondition"
        },
        {
          "name": "安装位置描述",
          "field": "installLocationDescription"
        },
        {
          "name": "结论",
          "field": "conclusion"
        }
      ]
    }]
  }, {
    "name": "绝缘接头保护器",
    "fields": [{
      "groupName": "基础数据",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        }, {
          "name": "标段名称",
          "field": "tendersName"
        }, {
          "name": "管线名称",
          "field": "pipelineName"
        }, {
          "name": "线路段名称",
          "field": "pipeSegmentName"
        }, {
          "name": "施工单位",
          "field": "constructUnitName"
        }, {
          "name": "施工日期",
          "field": "constructDate"
        },
        {
          "name": "监理单位",
          "field": "supervisionUnitName"
        }, {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        }, {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "采集日期",
          "field": "collectionDate"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "位置数据",
      "fileds": [{
        "name": "桩号",
        "field": "medianStakeCode"
      }, {
        "name": "相对桩位置(m)",
        "field": "relativeMileage"
      }, {
        "name": "X坐标",
        "field": "pointx"
      }, {
        "name": "Y坐标",
        "field": "pointy"
      }, {
        "name": "高程(m)",
        "field": "pointz"
      }]
    }, {
      "groupName": "绝缘接头保护数据",
      "fileds": [{
        "name": "设备编号",
        "field": "equipmentCode"
      }, {
        "name": "名称",
        "field": "equipmentName"
      }]
    }]
  }, {
    "name": "固态去耦合器",
    "fields": [{
      "groupName": "基础数据",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        }, {
          "name": "标段名称",
          "field": "tendersName"
        }, {
          "name": "管线名称",
          "field": "pipelineName"
        }, {
          "name": "线路段名称",
          "field": "pipeSegmentName"
        }, {
          "name": "施工单位",
          "field": "constructUnitName"
        }, {
          "name": "施工日期",
          "field": "constructDate"
        },
        {
          "name": "监理单位",
          "field": "supervisionUnitName"
        }, {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        }, {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "采集日期",
          "field": "collectionDate"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "位置数据",
      "fileds": [{
        "name": "桩号",
        "field": "medianStakeCode"
      }, {
        "name": "相对桩位置(m)",
        "field": "relativeMileage"
      }]
    }, {
      "groupName": "固态去耦合数据",
      "fileds": [{
        "name": "设备编号",
        "field": "equipmentCode"
      }, {
        "name": "名称",
        "field": "equipmentName"
      }]
    }]
  }, {
    "name": "阴极保护测试桩",
    "fields": [{
      "groupName": "基础数据",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        }, {
          "name": "标段名称",
          "field": "tendersName"
        }, {
          "name": "管线名称",
          "field": "pipelineName"
        }, {
          "name": "线路段名称",
          "field": "pipeSegmentName"
        }, {
          "name": "施工单位",
          "field": "constructUnitName"
        }, {
          "name": "施工日期",
          "field": "constructDate"
        },
        {
          "name": "监理单位",
          "field": "supervisionUnitName"
        }, {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        }, {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "采集日期",
          "field": "collectionDate"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "位置数据",
      "fileds": [{
        "name": "桩号",
        "field": "medianStakeCode"
      }, {
        "name": "相对桩位置(m)",
        "field": "relativeMileage"
      }, {
        "name": "X坐标",
        "field": "pointx"
      }, {
        "name": "Y坐标",
        "field": "pointy"
      }, {
        "name": "高程(m)",
        "field": "pointz"
      }]
    }, {
      "groupName": "测试桩数据",
      "fileds": [{
        "name": "测试桩编号",
        "field": "testStakeCode"
      }, {
        "name": "桩体结构",
        "field": "stakeStructureName"
      }, {
        "name": "安装位置描述",
        "field": "installLocationDescription"
      }, {
        "name": "埋设日期",
        "field": "burialDate"
      }, {
        "name": "桩功能",
        "field": "stakeFunctionName"
      }, {
        "name": "桩顶高度(m)",
        "field": "stakeTopHeight"
      }, {
        "name": "桩体形状",
        "field": "stakeShape"
      }]
    }]
  }, {
    "name": "极性排流器",
    "fields": [{
      "groupName": "基础数据",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        }, {
          "name": "标段名称",
          "field": "tendersName"
        }, {
          "name": "管线名称",
          "field": "pipelineName"
        }, {
          "name": "线路段名称",
          "field": "pipeSegmentName"
        }, {
          "name": "施工单位",
          "field": "constructUnitName"
        }, {
          "name": "施工日期",
          "field": "constructDate"
        },
        {
          "name": "监理单位",
          "field": "supervisionUnitName"
        }, {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        }, {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "采集日期",
          "field": "collectionDate"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "位置数据",
      "fileds": [{
        "name": "桩号",
        "field": "medianStakeCode"
      }, {
        "name": "相对桩位置(m)",
        "field": "relativeMileage"
      }, {
        "name": "X坐标",
        "field": "pointx"
      }, {
        "name": "Y坐标",
        "field": "pointy"
      }, {
        "name": "保护范围",
        "field": "protectionScope"
      }]
    }, {
      "groupName": "极性排流数据",
      "fileds": [{
          "name": "设备编号",
          "field": "equipmentCode"
        }, {
          "name": "名称",
          "field": "equipmentName"
        },
        {
          "name": "出厂编号",
          "field": "factoryNum"
        }, {
          "name": "制造商",
          "field": "manufacturer"
        }, {
          "name": "排流量(A)",
          "field": "dischargeFlow"
        },
        {
          "name": "最大排流量(A)",
          "field": "maxDischargeFlow"
        }, {
          "name": "平均排流量(A)",
          "field": "avgDischargeFlow"
        }, {
          "name": "最小排流量(A)",
          "field": "minDischargeFlow"
        }, {
          "name": "地床材料",
          "field": "groundBedMaterialName"
        }, {
          "name": "管地电位(V)",
          "field": "managePotential"
        }, {
          "name": "地床接地电位(V)",
          "field": "groundPotential"
        }, {
          "name": "投用日期",
          "field": "serviceDate"
        }, {
          "name": "预计失效日期",
          "field": "expirationDate"
        }, {
          "name": "生产日期",
          "field": "productDate"
        }, {
          "name": "排流用途",
          "field": "drainagePurposeName"
        }, {
          "name": "排流类型",
          "field": "drainageType"
        },
        {
          "name": "设计寿命(年)",
          "field": "designLife"
        }, {
          "name": "不排流时平均电位(V)",
          "field": "avgPotentialUndrain"
        }, {
          "name": "排流时平均电位(V)",
          "field": "avgPotentialDrain"
        }, {
          "name": "接地排流地床电阻(Ω)",
          "field": "earthingResistance"
        }
      ]
    }]
  }, {
    "name": "辅助阳极地床",
    "fields": [{
      "groupName": "基础数据",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        }, {
          "name": "标段名称",
          "field": "tendersName"
        }, {
          "name": "管线名称",
          "field": "pipelineName"
        }, {
          "name": "线路段名称",
          "field": "pipeSegmentName"
        }, {
          "name": "施工单位",
          "field": "constructUnitName"
        }, {
          "name": "施工日期",
          "field": "constructDate"
        },
        {
          "name": "监理单位",
          "field": "supervisionUnitName"
        }, {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        }, {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "采集日期",
          "field": "collectionDate"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "位置数据",
      "fileds": [{
        "name": "桩号",
        "field": "medianStakeCode"
      }, {
        "name": "相对桩位置(m)",
        "field": "relativeMileage"
      }, {
        "name": "X坐标",
        "field": "pointx"
      }, {
        "name": "Y坐标",
        "field": "pointy"
      }, {
        "name": "高程(m)",
        "field": "pointz"
      }]
    }, {
      "groupName": "阳极地床数据",
      "fileds": [{
          "name": "地床编号",
          "field": "groundBed"
        }, {
          "name": "安装位置描述",
          "field": "installLocationDescription"
        }, {
          "name": "埋深(m)",
          "field": "buriedDepth"
        }, {
          "name": "是否临时",
          "field": "isTemporary"
        }, {
          "name": "设计寿命(年)",
          "field": "designLife"
        }, {
          "name": "回填材料",
          "field": "backfillMaterialName"
        },
        {
          "name": "辅助阳极数量(个)",
          "field": "quantity"
        },
        {
          "name": "埋设方式",
          "field": "burialWayName"
        }, {
          "name": "总重(kg)",
          "field": "totalWeight"
        }, {
          "name": "电缆长度(m)",
          "field": "cableLength"
        }, {
          "name": "保护长度(m)",
          "field": "protectLength"
        }, {
          "name": "阳极材料类型",
          "field": "anodeMaterialType"
        }, {
          "name": "阳极材料规格",
          "field": "anodeMaterialSpec"
        }, {
          "name": "阳极电阻(Ω)",
          "field": "anodeResistance"
        }, {
          "name": "是否有注水系统",
          "field": "isWaterInjection"
        }, {
          "name": "是否有排气孔",
          "field": "isAirbleed"
        }, {
          "name": "埋设日期",
          "field": "burialDate"
        }, {
          "name": "地床连接阴保电源",
          "field": "connectionPower"
        }
      ]
    }]
  }, {
    "name": "标志桩安装检查信息记录",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        }, {
          "name": "标段名称",
          "field": "tendersName"
        }, {
          "name": "管线名称",
          "field": "pipelineName"
        }, {
          "name": "线路段/穿跨越",
          "field": "pipeSegmentOrCrossName"
        }, {
          "name": "施工单位",
          "field": "constructUnitName"
        },
        {
          "name": "监理单位",
          "field": "supervisionUnitName"
        }, {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        }, {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "采集日期",
          "field": "collectionDate"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "标志桩信息",
      "fileds": [{
          "name": "标志桩编号",
          "field": "markStakeCode"
        },
        {
          "name": "桩号",
          "field": "medianStakeCode"
        }, {
          "name": "相对桩位置(m)",
          "field": "relativeMileage"
        }, {
          "name": "X坐标",
          "field": "pointx"
        }, {
          "name": "Y坐标",
          "field": "pointy"
        }, {
          "name": "桩体结构",
          "field": "stakeStructureName"
        }, {
          "name": "埋设日期",
          "field": "burialDate"
        }, {
          "name": "桩功能",
          "field": "stakeFunctionName"
        }, {
          "name": "埋深(m)",
          "field": "burialDepth"
        }
      ]
    }]
  }, {
    "name": "电子标签信息记录",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        }, {
          "name": "标段名称",
          "field": "tendersName"
        }, {
          "name": "管线名称",
          "field": "pipelineName"
        }, {
          "name": "线路段/穿跨越",
          "field": "pipeSegmentOrCrossName"
        }, {
          "name": "施工单位",
          "field": "constructUnitName"
        },
        {
          "name": "监理单位",
          "field": "supervisionUnitName"
        }, {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        }, {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "采集日期",
          "field": "collectionDate"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "电子标签信息",
      "fileds": [{
          "name": "电子标签编号",
          "field": "electronicLabelCode"
        },
        {
          "name": "产品编号",
          "field": "productNum"
        }, {
          "name": "桩号",
          "field": "medianStakeCode"
        }, {
          "name": "X坐标",
          "field": "pointx"
        }, {
          "name": "Y坐标",
          "field": "pointy"
        }, {
          "name": "高程(m)",
          "field": "pointz"
        }, {
          "name": "埋设日期",
          "field": "burialDate"
        }, {
          "name": "特征点类型",
          "field": "featurePointTypeName"
        }, {
          "name": "埋深(m)",
          "field": "burialDepth"
        }
      ]
    }]
  }, {
    "name": "通信光缆人（手）孔位置信息记录",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        }, {
          "name": "标段名称",
          "field": "tendersName"
        }, {
          "name": "管线名称",
          "field": "pipelineName"
        }, {
          "name": "线路段/穿跨越",
          "field": "pipeSegmentOrCrossName"
        }, {
          "name": "施工单位",
          "field": "constructUnitName"
        },
        {
          "name": "监理单位",
          "field": "supervisionUnitName"
        }, {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        }, {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "采集日期",
          "field": "collectionDate"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "手孔信息",
      "fileds": [{
          "name": "孔编号",
          "field": "handHoleCode"
        },
        {
          "name": "孔名称",
          "field": "handHoleNameCodeName"
        }, {
          "name": "孔类型",
          "field": "handHoleTypeName"
        }, {
          "name": "桩号",
          "field": "medianStakeCode"
        }, {
          "name": "相对起始桩位置(m)",
          "field": "relativeMileage"
        }, {
          "name": "X坐标",
          "field": "pointx"
        }, {
          "name": "Y坐标",
          "field": "pointy"
        }, {
          "name": "高程(m)",
          "field": "pointz"
        }, {
          "name": "规格型号",
          "field": "handHoleSpecifications"
        }, {
          "name": "基础制造及安装情况",
          "field": "baseInstallSituation"
        }, {
          "name": "口圈及安装情况",
          "field": "circleInstallSituation"
        }, {
          "name": "材料类型",
          "field": "materialType"
        }, {
          "name": "光缆盘留长度(m)",
          "field": "stayLong"
        }, {
          "name": "是否放置电子标识",
          "field": "isElectronicMark"
        }, {
          "name": "检查验收结果",
          "field": "acceptanceResults"
        }
      ]
    }]
  }, {
    "name": "管道沿线地下障碍物信息记录",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        }, {
          "name": "标段名称",
          "field": "tendersName"
        }, {
          "name": "管线名称",
          "field": "pipelineName"
        }, {
          "name": "线路段/穿跨越",
          "field": "pipeSegmentOrCrossName"
        }, {
          "name": "施工单位",
          "field": "constructUnitName"
        },
        {
          "name": "监理单位",
          "field": "supervisionUnitName"
        }, {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        }, {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "采集日期",
          "field": "collectionDate"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "地下障碍物信息",
      "fileds": [{
          "name": "障碍物编号",
          "field": "obstacleCode"
        },
        {
          "name": "障碍物名称",
          "field": "obstacleName"
        }, {
          "name": "障碍物类型",
          "field": "obstacleTypeName"
        }, {
          "name": "桩号",
          "field": "medianStakeCode"
        }, {
          "name": "相对起始桩位置(m)",
          "field": "relativeMileage"
        }, {
          "name": "X坐标",
          "field": "pointx"
        }, {
          "name": "Y坐标",
          "field": "pointy"
        }, {
          "name": "高程(m)",
          "field": "pointz"
        }, {
          "name": "所属单位",
          "field": "subordinateUnit"
        }, {
          "name": "地址",
          "field": "address"
        }, {
          "name": "联系人",
          "field": "contacts"
        }, {
          "name": "电话",
          "field": "telephone"
        }, {
          "name": "最小间距(m)",
          "field": "minDistance"
        }, {
          "name": "是否与管道交叉",
          "field": "isThroughPipeline"
        }
      ]
    }]
  }, {
    "name": "管道沿线水工保护信息记录",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        }, {
          "name": "标段名称",
          "field": "tendersName"
        }, {
          "name": "管线名称",
          "field": "pipelineName"
        }, {
          "name": "线路段/穿跨越",
          "field": "pipeSegmentOrCrossName"
        }, {
          "name": "施工单位",
          "field": "constructUnitName"
        },
        {
          "name": "监理单位",
          "field": "supervisionUnitName"
        }, {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        }, {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "采集日期",
          "field": "collectionDate"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "水工保护信息",
      "fileds": [{
          "name": "水工保护编号",
          "field": "hydraulicProtectionCode"
        },
        {
          "name": "水工保护类型",
          "field": "hydraulicProtectionTypeName"
        }, {
          "name": "水工保护名称",
          "field": "hydraulicProtectionName"
        }, {
          "name": "桩号",
          "field": "medianStakeCode"
        }, {
          "name": "相对起始桩位置(m)",
          "field": "relativeMileage"
        }, {
          "name": "起点X坐标",
          "field": "startPointx"
        }, {
          "name": "起点Y坐标",
          "field": "startPointy"
        }, {
          "name": "终点X坐标",
          "field": "endPointx"
        }, {
          "name": "终点Y坐标",
          "field": "endPointy"
        }, {
          "name": "结构尺寸",
          "field": "structureSize"
        }, {
          "name": "光缆盘留长度(m)",
          "field": "engineerQuatity"
        }, {
          "name": "水工保护材料",
          "field": "hydraulicProtectionMaterialName"
        }, {
          "name": "检查验收日期",
          "field": "acceptDate"
        }, {
          "name": "检查结论",
          "field": "inspectionFindings"
        }, {
          "name": "施工机组",
          "field": "workUnitName"
        }
      ]
    }]
  }, {
    "name": "套管",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
          "name": "项目名称",
          "field": "projectName"
        }, {
          "name": "标段名称",
          "field": "tendersName"
        }, {
          "name": "管线名称",
          "field": "pipelineName"
        }, {
          "name": "线路段/穿跨越",
          "field": "pipeSegmentOrCrossName"
        }, {
          "name": "施工单位",
          "field": "constructUnitName"
        },
        {
          "name": "监理单位",
          "field": "supervisionUnitName"
        }, {
          "name": "监理工程师",
          "field": "supervisionEngineer"
        }, {
          "name": "采集人员",
          "field": "collectionPerson"
        }, {
          "name": "采集日期",
          "field": "collectionDate"
        }, {
          "name": "审核状态",
          "field": "approveStatus"
        }
      ]
    }, {
      "groupName": "套管信息",
      "fileds": [{
          "name": "起始桩号",
          "field": "startMedianStakeCode"
        },
        {
          "name": "相对起始桩位置(m)",
          "field": "startRelativeMileage"
        }, {
          "name": "结束桩号",
          "field": "endMedianStakeCode"
        }, {
          "name": "相对结束桩位置(m)",
          "field": "endRelativeMileage"
        }, {
          "name": "起点X坐标",
          "field": "startPointx"
        }, {
          "name": "起点Y坐标",
          "field": "startPointy"
        }, {
          "name": "终点X坐标",
          "field": "endPointx"
        }, {
          "name": "终点Y坐标",
          "field": "endPointy"
        }, {
          "name": "套管类型",
          "field": "casingPipeTypeName"
        }, {
          "name": "套管长度(m)",
          "field": "casingPipeLength"
        }, {
          "name": "套管规格",
          "field": "casingPipeSpecifications"
        }, {
          "name": "施工日期",
          "field": "constructDate"
        }
      ]
    }]
  }, {
    "name": "防腐补口检查信息记录",
    "fields": [{
      "groupName": "基本信息",
      "fileds": [{
          "name": "项目名称",
          "field": "project_name"
        }, {
          "name": "标段名称",
          "field": "tenders_name"
        }, {
          "name": "管线名称",
          "field": "pipeline_name"
        }, {
          "name": "线路段/穿跨越",
          "field": "pipe_segment_or_cross_name"
        }, {
          "name": "施工单位",
          "field": "construct_unit_name"
        },
        {
          "name": "监理单位",
          "field": "supervision_unit_name"
        }, {
          "name": "监理工程师",
          "field": "supervision_engineer"
        }, {
          "name": "采集人员",
          "field": "collection_person"
        }, {
          "name": "采集日期",
          "field": "collection_date"
        }, {
          "name": "审核状态",
          "field": "approve_status_name"
        }
      ]
    }, {
      "groupName": "防腐补口检查信息",
      "fileds": [{
          "name": "焊口编号",
          "field": "weld_code"
        },
        {
          "name": "补口材料批号",
          "field": "buckle_material_batch_num"
        }, {
          "name": "补口日期",
          "field": "buckle_date"
        }, {
          "name": "补口防腐类型",
          "field": "buckle_anticorrosive_type_name"
        }, {
          "name": "防腐等级",
          "field": "buckle_anticorrosive_grade_name"
        }, {
          "name": "除锈等级",
          "field": "derusting_grade_name"
        }, {
          "name": "管口清理",
          "field": "pipe_mouth_clean_name"
        }, {
          "name": "喷砂除锈",
          "field": "sandblasting_and_derusting_name"
        }, {
          "name": "管口预热",
          "field": "pipe_mouth_preheat_name"
        }, {
          "name": "环氧底漆",
          "field": "epoxy_primer_name"
        }, {
          "name": "喷拷",
          "field": "baking_check_name"
        }, {
          "name": "轴向搭接",
          "field": "overlap_check_name"
        }, {
          "name": "外观检查",
          "field": "appearance_check_name"
        }, {
          "name": "电火花捡漏",
          "field": "electric_spark_leak_detection_name"
        }, {
          "name": "补口结论",
          "field": "buckle_conclusion_name"
        }, {
          "name": "防腐工",
          "field": "anticorrosion"
        }
      ]
    }]
  }, {
    "name": "防腐补口剥离强度试验",
    "fields": [{
      "groupName": "防腐补口剥离强度试验信息",
      "fileds": [{
          "name": "项目名称",
          "field": "project_name"
        }, {
          "name": "标段名称",
          "field": "tenders_name"
        }, {
          "name": "管线名称",
          "field": "pipeline_name"
        }, {
          "name": "线路段/穿跨越",
          "field": "pipe_segment_or_cross_name"
        }, {
          "name": "焊口编号",
          "field": "weld_code"
        },
        {
          "name": "相对焊口里程（m）",
          "field": "relative_mileage"
        }, {
          "name": "剥离方法",
          "field": "separate_method"
        }, {
          "name": "对PE剥离强度（N/cm）",
          "field": "pe_strength"
        }, {
          "name": "对光管剥离强度（N/cm）",
          "field": "light_peel_strength"
        }, {
          "name": "实验结果",
          "field": "test_result"
        }, {
          "name": "实验日期",
          "field": "test_date"
        }, {
          "name": "施工单位",
          "field": "construct_unit_name"
        },
        {
          "name": "监理单位",
          "field": "supervision_unit_name"
        }, {
          "name": "监理工程师",
          "field": "supervision_engineer"
        }, {
          "name": "采集人员",
          "field": "collection_person"
        }, {
          "name": "采集日期",
          "field": "collection_date"
        }, {
          "name": "审核状态",
          "field": "approve_status_name"
        }

      ]
    }]

  }, {
    "name": "防腐补伤信息记录",
    "fields": [{
      "groupName": "防腐补伤信息",
      "fileds": [{
          "name": "项目名称",
          "field": "project_name"
        }, {
          "name": "标段名称",
          "field": "tenders_name"
        }, {
          "name": "管线名称",
          "field": "pipeline_name"
        }, {
          "name": "线路段/穿跨越",
          "field": "pipe_segment_or_cross_name"
        }, {
          "name": "焊口编号",
          "field": "weld_code"
        },
        {
          "name": "相对焊口位置（m）",
          "field": "relative_mileage"
        }, {
          "name": "补伤部位",
          "field": "anticorrosion_position"
        }, {
          "name": "补伤方式",
          "field": "code_name"
        }, {
          "name": "补伤材料描述",
          "field": "anticorrosion_describe"
        }, {
          "name": "检测电压（KV）",
          "field": "detection_voltage"
        }, {
          "name": "施工单位",
          "field": "construct_unit_name"
        },
        {
          "name": "监理单位",
          "field": "supervision_unit_name"
        }, {
          "name": "补伤人",
          "field": "construction_person"
        }, {
          "name": "监理工程师",
          "field": "supervision_engineer"
        }, {
          "name": "采集人员",
          "field": "collection_person"
        }, {
          "name": "采集日期",
          "field": "collection_date"
        }, {
          "name": "审核状态",
          "field": "approve_status_name"
        }

      ]
    }]

  }, {
    "name": "牺牲阳极电参数测试信息记录",
    "fields": [{
      "groupName": "牺牲阳极电参数测试记录信息",
      "fileds": [{
          "name": "项目名称",
          "field": "project_name"
        }, {
          "name": "标段名称",
          "field": "tenders_name"
        }, {
          "name": "测试桩编号",
          "field": "test_stake_code"
        }, {
          "name": "管道对地自然电位(V)",
          "field": "natural_potential"
        }, {
          "name": "阳极1开路电位(V)",
          "field": "open_circuit_potential_one"
        },
        {
          "name": "阳极2开路电位(V)",
          "field": "open_circuit_potential_two"
        }, {
          "name": "管道对地保护电位(V)",
          "field": "protective_potential"
        }, {
          "name": "阳极组输出电流(mA)",
          "field": "group_output_current"
        }, {
          "name": "阳极1输出电流(mA)",
          "field": "output_current_one"
        }, {
          "name": "阳极2输出电流(mA)",
          "field": "output_current_two"
        }, {
          "name": "阳极1接地电阻(Ω)",
          "field": "earthing_resistance_one"
        }, {
          "name": "阳极2接地电阻(Ω)",
          "field": "earthing_resistance_two"
        }, {
          "name": "施工单位",
          "field": "construct_unit_name"
        },
        {
          "name": "监理单位",
          "field": "supervision_unit_name"
        }, {
          "name": "监理工程师",
          "field": "supervision_engineer"
        }, {
          "name": "测试人员",
          "field": "test_person"
        }, {
          "name": "测试日期",
          "field": "test_date"
        }, {
          "name": "审核状态",
          "field": "approve_status_name"
        }

      ]
    }]
  }, {
    "name": "外加电流电参数测试信息记录",
    "fields": [{
      "groupName": "外加电流电参数测试记录信息",
      "fileds": [{
          "name": "项目名称",
          "field": "project_name"
        }, {
          "name": "标段名称",
          "field": "tenders_name"
        }, {
          "name": "测试桩编号",
          "field": "test_stake_code"
        }, {
          "name": "测试区段",
          "field": "test_region"
        }, {
          "name": "测试日期",
          "field": "test_date"
        }, {
          "name": "通用日期",
          "field": "currency_date"
        },
        {
          "name": "极化时间",
          "field": "polarization_date"
        }, {
          "name": "投产前管道对地自然电位(V)",
          "field": "natural_potential"
        }, {
          "name": "投产前阳极地床接地电阻(Ω)",
          "field": "earthing_resistance"
        }, {
          "name": "投产后管道保护标准电位(V)",
          "field": "standard_voltage"
        }, {
          "name": "投产前直流电源电位/电压(V)",
          "field": "direct_current_voltage"
        }, {
          "name": "投产后管道保护实测电位(V)",
          "field": "measured_voltage"
        }, {
          "name": "投产后管道保护标准电流(mA)",
          "field": "standard_current"
        }, {
          "name": "投产后管道保护实测电流(mA)",
          "field": "measured_current"
        }, {
          "name": "施工单位",
          "field": "unit_name"
        },
        {
          "name": "监理单位",
          "field": "supervision_unit_name"
        }, {
          "name": "监理工程师",
          "field": "supervision_engineer"
        }, {
          "name": "审核状态",
          "field": "approve_status_name"
        }
      ]
    }]
  }, {
    "name": "伴行路",
    "fields": [{
      "groupName": "外加电流电参数测试记录信息",
      "fileds": [{
        "name": "项目名称",
        "field": "project_name"
      }, {
        "name": "标段名称",
        "field": "tenders_name"
      }, {
        "name": "管线名称",
        "field": "pipeline_name"
      }, {
        "name": "施工单位",
        "field": "construct_unit_name"
      }, {
        "name": "监理单位",
        "field": "supervision_unit_name"
      }, {
        "name": "监理工程师",
        "field": "supervision_engineer"
      }, {
        "name": "采集人员",
        "field": "collection_person"
      }, {
        "name": "采集日期",
        "field": "collection_date"
      }, {
        "name": "审核状态",
        "field": "approve_status_name"
      }]
    }, {
      "groupName": "伴行道路数据",
      "fileds": [{
        "name": "伴行道路编号",
        "field": "concomitant_road_code"
      }, {
        "name": "伴行道路名称",
        "field": "concomitant_road_name"
      }, {
        "name": "长度(m)",
        "field": "concomitant_road_length"
      }, {
        "name": "路面类型",
        "field": "pavement_type_name"
      }, {
        "name": "路基宽度(mm)",
        "field": "road_width"
      }, {
        "name": "开工日期",
        "field": "commence_date"
      }, {
        "name": "完工日期",
        "field": "completion_date"
      }]
    }]
  }
];

fieldConfigs.forEach(function (item) {
  item.fields.push({
    "groupName": "其他信息",
    "fileds": [{
      "name": "备注",
      "field": "remarks"
    }]
  })
})